name: ✨ Feature Request
description: Suggest a new feature or enhancement for the ECS Game Engine
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
assignees: ["danjdewhurst"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please check that you've completed these steps before submitting the feature request.
      options:
        - label: I have searched existing issues and discussions to ensure this feature hasn't been requested already
          required: true
        - label: I have read the project roadmap and this feature isn't already planned
          required: true
        - label: This feature aligns with the project's goals as an ECS game engine
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe what problem this feature would solve.
      placeholder: I'm frustrated when... / I need to... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Small change or addition
        - Medium - Moderate change requiring some refactoring
        - High - Major feature requiring significant changes
        - Unknown - I'm not sure
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature. How would you use it in your game/application?
      placeholder: In my game, I need to...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design (Optional)
      description: If you have ideas about how the API should look, provide a code example.
      render: typescript
      placeholder: |
        // Example API design
        world.someNewMethod({
          option: 'value'
        });
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to implementing this feature?
      options:
        - label: I would be willing to implement this feature myself
        - label: I would be willing to help with testing
        - label: I would be willing to help with documentation
        - label: I can provide use case testing and feedback

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples that would help explain your feature request.
      placeholder: Any additional information...
    validations:
      required: false